version: "3.10"

services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
        environment:
            - "DJANGO_SECRET_KEY=df9ix0bXsgBF4mhINlp9R68KShUQU7LAYQ5LwYeX6G3lrvJmeVA"
            - "DJANGO_DEBUG=True"
    db:
        image: postgres:13
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
    postgres_data: